services:
  api:
    build: .
    volumes:
      - ./app:/app/app
      - ./data:/app/data
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:15
    restart: always
    ports:
      - "55432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  test:
    build: .
    command: ["pytest", "app/tests"]
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./app:/app/app

volumes:
  pgdata: